### ISSUE TITLE
bug smartviera panasonic dans gladys

### ISSUE THREAD

**Issue by Lio78** [vincentBesseau/gladys-viera#1]
Bonjour,

Je viens d'installer le module dans Gladys.
Tout fonctionne correctement sauf pour allumer la télé.
La télé allumée, j'arrive à l'éteindre mais la télé éteinte ( en veille ), je n'arrive pas à l'allumer.

Cordialement.

Lionel.

**Comment by vincentBesseau** [comment]
Salut ! 
J'ai vu ton post sur le forum !
Hésite pas a me taguer quand tu as besoin (spenceur1) :-).

Peux tu me fournir des informations complémentaire (log, version gladys, modele TV) ?

**Comment by vincentBesseau** [comment]
Problème non lié au module : 
https://community.gladysassistant.com/t/resolu-module-panasonic-smart-viera/4627/15
